version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: ledger_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_SUPER_USER} # супер юзер для накатывания миграций
      POSTGRES_PASSWORD: ${DB_SUPER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ledger_network

  ledger-app-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
    entrypoint: [ "/migrate" ]
    networks:
      - ledger_network

  redis:
    image: redis:7-alpine
    container_name: ledger_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ledger_network
volumes:
  postgres_data:

networks:
  ledger_network:
    driver: bridge