.PHONY: gen

gen:
	mkdir -p gen/go/ledger

	protoc -I api/ledger \
		--go_out=gen/go/ledger --go_opt=paths=source_relative \
		--go-grpc_out=gen/go/ledger --go-grpc_opt=paths=source_relative \
		api/ledger/ledger.proto