resolver 127.0.0.11 valid=10s ipv6=off;



upstream grpc_backend {
    server gateway:50051 max_fails=0;
    keepalive 100;
}

server {
    listen 80;
    http2 on;

    server_name localhost;

    access_log off;
    error_log /dev/stderr notice;

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        deny all;
    }

    location / {
        grpc_pass grpc://grpc_backend;

        grpc_read_timeout 15s;
        grpc_send_timeout 15s;
        grpc_connect_timeout 5s;

        error_page 502 = /grpc_errors;
    }

    location = /grpc_errors {
        grpc_set_header grpc-status 2;
        grpc_set_header grpc-message "Internal Server Error / Upstream unavailable";
        return 204;
    }
}
