resolver 127.0.0.11 valid=10s ipv6=off;

upstream ledger_backend {
    zone ledger_backend 64k;
    least_conn;
    server gateway:50051 resolve;
}

server {
    listen 80;
    http2 on;

    server_name localhost;

    access_log /dev/stdout;
    error_log /dev/stderr notice;

    grpc_read_timeout 5s;
    grpc_send_timeout 5s;

    location / {
        grpc_pass grpc://ledger_backend;
        error_page 502 = /grpc_errors;
    }

    location = /grpc_errors {
        grpc_set_header grpc-status 2;
        grpc_set_header grpc-message "Internal Server Error / Upstream unavailable";
        return 204;
    }
}