FROM golang:1.26.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM alpine:3.21
WORKDIR /app

COPY --from=builder /app/worker .

EXPOSE 6767
CMD ["./worker"]
